# This file was generated by GoReleaser. DO NOT EDIT.
cask "proc-man" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "653dae2860914904e34837ae2727c14c78f59f27deefe096d5bbb5b430d9659f"
      url "https://github.com/ericwooley/proc-man/releases/download/v#{version}/proc-man_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "37b6ffeac880ed2eecb74579ab905aaefc2ee2c789cc5ae884cf621b7a43f566"
      url "https://github.com/ericwooley/proc-man/releases/download/v#{version}/proc-man_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2e013a1ace4c61e0dbbae65ccdf6cebd27a030573d20e767196bdf06da770a55"
      url "https://github.com/ericwooley/proc-man/releases/download/v#{version}/proc-man_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b3fae879c5d2dfa5728fbe87b3e7745213015e907bf71cc640a2b870d19c21ad"
      url "https://github.com/ericwooley/proc-man/releases/download/v#{version}/proc-man_#{version}_linux_arm64.tar.gz"
    end
  end

  name "proc-man"
  desc "Manage local development processes and logs"
  homepage "https://github.com/ericwooley/proc-man"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "proc-man"

  postflight do
    system_command "#{staged_path}/proc-man", args: ["daemon", "install", "--now"]
  end

  uninstall_preflight do
    system_command "#{staged_path}/proc-man", args: ["daemon", "uninstall"]
  end

  # No zap stanza required

end
