# This file was generated by GoReleaser. DO NOT EDIT.
cask "proc-man" do
  version "1.1.4"

  on_macos do
    on_intel do
      sha256 "87f012e38721ed3df530ba08f0cff2a99e04f6b1ccde924edaef880c0678b779"
      url "https://github.com/ericwooley/proc-man/releases/download/v#{version}/proc-man_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "51d4621a91ce9b4b09cd126a651efd39a74219988d3a9501967e11b4a7ff076e"
      url "https://github.com/ericwooley/proc-man/releases/download/v#{version}/proc-man_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "873ba0373efd9a9785207163bc6084f02d794684df5e1913d295d74ed0cf17ec"
      url "https://github.com/ericwooley/proc-man/releases/download/v#{version}/proc-man_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "28d6129e745c7912b06084eda12760ab65c7a091b9f768fc94ea3fd358877a80"
      url "https://github.com/ericwooley/proc-man/releases/download/v#{version}/proc-man_#{version}_linux_arm64.tar.gz"
    end
  end

  name "proc-man"
  desc "Manage local development processes and logs"
  homepage "https://github.com/ericwooley/proc-man"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "proc-man"

  postflight do
    if OS.mac?
      executable = "#{staged_path}/proc-man"
      replacement = "#{staged_path}/.proc-man-replacement"
      FileUtils.copy_file executable, replacement
      FileUtils.chmod 0755, replacement
      FileUtils.mv replacement, executable, force: true
    end
    system_command "#{staged_path}/proc-man", args: ["daemon", "install", "--now"]
  end

  uninstall_preflight do
    system_command "#{staged_path}/proc-man", args: ["daemon", "uninstall"]
  end

  # No zap stanza required

end
