# This file was generated by GoReleaser. DO NOT EDIT.
cask "proc-man" do
  version "1.0.2"

  on_macos do
    on_intel do
      sha256 "d7a2eb47cfe4b454d72d1ca394c494c88186e124e66e3529ea9cc97197972980"
      url "https://github.com/ericwooley/proc-man/releases/download/v#{version}/proc-man_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bf518f750e2598aaa44afee7ccf1f3964a32cba92d9dce795764a3d8e4429d35"
      url "https://github.com/ericwooley/proc-man/releases/download/v#{version}/proc-man_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b4919f92d3ecffd9b92f8a982d64cf76a28e6227f79f6f52a764f7ac859ae198"
      url "https://github.com/ericwooley/proc-man/releases/download/v#{version}/proc-man_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1b4649a9bb3e8fa01ba8071dadf1d8df78e9fc4cf64b1926505827303ba8bd8f"
      url "https://github.com/ericwooley/proc-man/releases/download/v#{version}/proc-man_#{version}_linux_arm64.tar.gz"
    end
  end

  name "proc-man"
  desc "Manage local development processes and logs"
  homepage "https://github.com/ericwooley/proc-man"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "proc-man"

  # No zap stanza required

end
